# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Data Storyteller"
description: > # this means to ignore newlines until "email:"
   Dreamgonfly's blog

email: dreamgonfly@gmail.com
#blog logo
logo: "/assets/images/dragonfly_moon.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Dreamgonfly'
author: 'Dreamgonfly'
author_image: "/assets/images/dragonfly_moon.jpg"

paginate:	5

url: "https://dreamgonfly.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dreamgonfly'

#fill in disqus shortname to use disqus
disqus: dreamgonfly-blog

google_analytics: UA-91026007-2

# social icons and sharing options
social:
  - icon:	twitter
    url:	#https://twitter.com/dirkfabisch
    desc: #Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	#https://facebook.com/???
    desc: #Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dreamgonfly
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

markdown: kramdown